### DISCUSSION TITLE
Stuck on v5.8.0.0

### DISCUSSION THREAD

**Discussion by 8666** [doitandbedone/ispyagentdvr-docker#786] [General]
I can not upgrade my docker installation. 

My docker compose looks like this:

```
version: '3.7'
services:
  agentdvr:
    image: doitandbedone/ispyagentdvr:5.8.0.0
    container_name: agentdvr
    restart: always
    ports:
      - 443:8443
      - 8090:8090
      - 3478:3478/udp
      - 50000-50010:50000-50010/udp
    volumes:
      - ./config:/agent/Media/XML/
      - ./models:/agent/Models/
      - /mnt/fast/CCTV/media:/agent/Media/WebServerRoot/Media/
      - /mnt/slow/CCTV/media/archive:/agent/Media/WebServerRoot/Old/
      - /mnt/fast/CCTV/commands:/agent/Commands/
     devices:
      - /dev/dri:/dev/dri
    logging:
      options:
        tag: "dvr"

````

When I start docker-compose with newer image I get
````
[+] Running 1/0
 ✔ Container agentdvr  Recreated                                                                                   0.0s
Attaching to agentdvr

````

docker stats:
````
CONTAINER ID   NAME                    CPU %     MEM USAGE / LIMIT    MEM %     NET I/O           BLOCK I/O         PIDS
3b29360678ba   agentdvr                0.00%     59.07MiB / 12.7GiB   0.45%     876B / 0B         0B / 0B           10
````

There are no logs, by official docs there should be json logs in media folder but I only have video and audio subfolders there
