### ISSUE TITLE
Support Arm/ Arm64

### ISSUE THREAD

**Issue by ispysoftware** [doitandbedone/ispyagentdvr-docker#162]
Is there a way to detect and install the Arm/ Arm64 binaries and dependencies in Docker if it's Arm hardware?

**Comment by doitandbedone** [comment]
Usually pick the image as they need to. There might be a way if I use
docker compose, not too familiar yet I'll look into it. For now the
standard is to pick the correct image. I can add instructions on the readme.

**Comment by KemyszPL** [comment]
I'm also facing this issue. I'm trying to install it on my Raspberry Pi, however I'm getting the `exec user process caused: exec format error`, which basically means the architecture is not supported. Please add instructions to the readme, as I'm confused on what I should do.

**Comment by ispysoftware** [comment]
There's an arm download and instructions on the download page on the website

**Comment by doitandbedone** [comment]
There's currently no support for ARM for docker, however you may install ispy directly, please follow instructions here:
https://www.ispyconnect.com/download.aspx

**Comment by nogueirasa** [comment]
Hello @doitandbedone ,
Very nice work, but tag "multi-arch" didn't work for rpi4 4GB with:

Raspberry Pi OS Lite
Release date: January 11th 2021
Kernel version: 5.4

with docker-compose:

```
  agentdvr:
    container_name: agentdvr
    image: doitandbedone/ispyagentdvr:multi-arch
    volumes:
      - /home/pi/agentdvr:/agent/Media/XML
      - /home/pi/agentdvr/media:/agent/Media/WebServerRoot/Media
      - /home/pi/agentdvr/commands:/agent/Commands
    restart: always
    network_mode: host
```

Getting error:
`standard_init_linux.go:219: exec user process caused: exec format error`

I'm also tryed with the digest code of multi-arch armv7:

`doitandbedone/ispyagentdvr@sha256:1f2a3f30a0cd40e5624a2e52ede318d588b4b95c61b7d965c7ab374072ed15b2`
