### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by adman120** [doitandbedone/ispyagentdvr-docker#357]
Affected Version
Found at top left "Server Menu" with a server/stack icon. A pop up will be opened, should be in bold letters to the right of your server name. [e.g. v3.0.0.0]

I'm unable to login. I'm using docker image doitandbedone/ispyagentdvr:latest within Docker Swarm.

Describe the bug

When accessing http://localhost:8090 I see the spinning wheel and then a failure connecting to agent and am presented with the option to retry.

Steps To Reproduce

Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behavior

Reproduction rate
How often does this happen in % [e.g. 100% or 50%]

100%

Screenshots

image

Host System Information (where ispy agent is running/hosted):

OS: [e.g. macOS Catalina 10.15.7, Windows 10, Ubuntu 20.04.1 LTS]
Docker Swarm

Client System Information (device accessing the web portal, if applicable):

OS: [e.g. macOS Catalina 10.15.7, iOS 8.1, Windows 10, Android 10, Ubuntu 20.04.1 LTS]
Browser [e.g. stock browser, safari, chrome]
Browser Version [e.g. 86.0.4240.111 (Official Build) (x86_64)]
Additional Information
Add any other information about the problem here. This could include configuration files, video/images that may be causing the issue.

DOCKER COMPOSE

 ispy:
    image: doitandbedone/ispyagentdvr:latest
    container_name: ispy
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - $DOCKERDIR/appdata/ispy/config:/agent/Media/XML/ 
      - /mnt/NAS/ispy:/agent/Media/WebServerRoot/Media/
      - $DOCKERDIR/appdata/ispy/commands:/agent/Commands/
    networks:
      - t2_proxy
    ports:
      - 8090:8090/tcp
      - 3478:3478/tcp
      - 50000-50010:50000-50010/udp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.ispy-rtr.entrypoints=https"
      - "traefik.http.routers.ispy-rtr.rule=Host(`ispy.$DOMAINNAME0`)"
      ## Middlewares
      - "traefik.http.routers.ispy-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.ispy-rtr.service=ispy-svc"
      ## HTTP Services
      - "traefik.http.services.ispy-svc.loadbalancer.server.port=8090"
      - "traefik.http.services.ispy-svc.loadbalancer.server.port=3478"

**Comment by ispysoftware** [comment]
this was posted in another issue:

I was starting the image from docker (see attached pic), but for a change I used the command found on the ispyconnect web site and now I can log into the agentdvr.

docker run -it -p 8090:8090 -p 3478:3478/udp -p 50000-50010:50000-50010/udp --name agentdvr doitandbedone/ispyagentdvr:latest

**Comment by adman120** [comment]
Is there a reason that launching there are issues when using compose?

**Comment by ispysoftware** [comment]
what issues?

**Comment by adman120** [comment]
@doitandbedone is there a reason that I would be having issues launching in compose mode? Like I get to 
![image](https://user-images.githubusercontent.com/3687746/147117634-6b507b7f-9cd0-4b0e-80f4-3685e9b9d306.png)
and im stuck

**Comment by doitandbedone** [comment]
I noticed you listed the wrong port type:
- 3478:3478/tcp
This port is used as udp for the TURN server to work. Try correcting this.

**Comment by AMD-NICK** [comment]
Spent about 6 hours on this. It's working `docker-compose.yml` configured to use iSpy with Traefik.

Notes:
- I can't setup https. It's probably the main problem that caused me to spend so much time. With https I've got 406 and 502 errors all time
- At the bottom of the file you can see deepstack section. I think it will work fine, but I have no tested it yet
- For some reasons you SHOULD publish 3478 port and I can't hide it behind Traefik

```yaml
version: '3'

networks:
  proxy: # создана в docker-compose traefik'а
    name: proxy
    external: true

services:
  ispy:
    image: doitandbedone/ispyagentdvr:latest
    volumes:
      - $PWD/config/:/agent/Media/XML/
      - $PWD/media/:/agent/Media/WebServerRoot/Media/
      - $PWD/commands/:/agent/Commands/
    ports:
      # - 8090:8090
      # - 50000-50010:50000-50010/udp
      - 3478:3478/udp # без этого бесконечная загрузка Agent страницы. Как же сука сложно было догадаться
    networks:
      - proxy
    tty: true # включает более детальный лог в консоли. Лол
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ispy_route.rule=Host(`ispy.domain.com`)"
      - "traefik.http.routers.ispy_route.entrypoints=web" # никак не смог заставить работать с web-secure. Либо 502, либо 406
      # - traefik.http.routers.ispy_route.tls=true # не работает сука
      # - "traefik.http.routers.ispy_route.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.ispy_route.service=ispy_service"
      # - traefik.http.services.ispy_service.loadbalancer.server.scheme=https
      - "traefik.http.services.ispy_service.loadbalancer.server.port=8090"

  # deepstack:
  #   image: deepquestai/deepstack:latest
  #   volumes:
  #     - $PWD/deepstack:/datastore
  #   environment:
  #     - VISION-FACE=True
  #     - MODE=Medium # Low, Medium, High
  #   # ports:
  #   #   - 8896:5000

  #   networks:
  #     - proxy
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.dstack.rule=Host(`deepstack.domain.com`)
  #     - traefik.http.routers.dstack.entrypoints=web-secure
  #     - traefik.http.routers.dstack.tls.certresolver=mytlschallenge

```

Press ❤️ to pay respects :)
