### ISSUE TITLE
Need your help to create an Agent DVR addon for Home Assistant

### ISSUE THREAD

**Issue by DivanX10** [doitandbedone/ispyagentdvr-docker#507]
Your program is great, but there is not enough addon for Home Assistant and I would like Agent DVR to have an addon for Home Assistant. I've learned how to create simple things so far, but I haven't learned how to transfer settings from an addon to a container or mount folders, and I don't understand how to do it. I created the Agent DVR addon and ran into a problem. I do not know how to mount folders from Home Assistant. More precisely, I know how to mount folders in the Docker Container itself, but I don't know how to implement it in the Agent DVR addon. The addon itself is launched and Agent DVR is working properly. Could you help in creating the Agent DVR addon? You can take all the files [here](https://github.com/DivanX10/Home-Assistant-Add-on-DeepStack-Edge/tree/main/agentdvr)

The appearance of the Agent DVR addon
![image](https://user-images.githubusercontent.com/64090632/195932712-e55a944b-858a-4fa9-b0ec-6722b7d3a55e.png)
![image](https://user-images.githubusercontent.com/64090632/195933360-19aab710-90e0-4006-9314-35be92345759.png)

I was thinking of using Stacks to add Agent DVR to Docker Portainer since it works successfully, but it only works if we manually insert this code into Stacks

![image](https://user-images.githubusercontent.com/64090632/195933783-4cb35e34-d19a-49ca-b8d0-489c46434312.png)

```
version: "3.7"
services:
  agentdvr_4.2.9.0:
    image: doitandbedone/ispyagentdvr:4.2.9.0
    container_name: AgentDVR_4.2.9.0
    privileged: true
    restart: always
    ports:
      - "8090:8090"
      - "3478:3478/udp"
      - "50000-50010:50000-50010/udp"
    volumes:
      - /mnt/data/supervisor/homeassistant/AgentDVR/Commands:/agent/Commands
      - /mnt/data/supervisor/homeassistant/AgentDVR/Media:/agent/Media/WebServerRoot/Media
      - /mnt/data/supervisor/homeassistant/AgentDVR/Config:/agent/Media/XML
```
