### ISSUE TITLE
[Compose] Container never starts

### ISSUE THREAD

**Issue by UntouchedWagons** [doitandbedone/ispyagentdvr-docker#537]
**Affected Version**

Don't know, container never starts

**Describe the bug**

Container doesn't start

**Steps To Reproduce**
1. Run `docker compose up`
2. Nothing happens

**Expected behavior**

The container to start

**Reproduction rate**
100%

**Screenshots**

![MobaXterm_91mNDyh62b](https://user-images.githubusercontent.com/160996/210901104-49c41012-e673-40b5-b9fd-0f098af090e9.png)

**Host System Information (where ispy agent is running/hosted):**
 - OS: Ubuntu 22.04

**Additional Information**
```cat docker-compose.yaml
version: '3.3'
services:
  ispyagentdvr:
    ports:
      - '8090:8090'
      - '50000-50010:50000-50010/udp'
    volumes:
      - ispyagentdvr-commands:/agent/Commands/'
      - ispyagentdvr-data:/agent/Media/XML/'
      - ispyagentdvr-media:/agent/Media/WebServerRoot/Media/'
    environment:
      - TZ=America/Toronto
    container_name: ispyagentdvr
    image: doitandbedone/ispyagentdvr
    networks:
      - default
      - docker_default

volumes:
  ispyagentdvr-data:
  ispyagentdvr-commands:
  ispyagentdvr-media:

networks:
  default:
  docker_default:
    external: true
```

**Comment by ErickGandara** [comment]
Volumes are empty. They should be filled with the corresponding values. Unless you remived them for this post?

**Comment by UntouchedWagons** [comment]
`ispyagentdvr-media` is an NFS volume which would normally use my real name, but the other two volumes are bog standard volumes that docker manages for me.

**Comment by doitandbedone** [comment]
Not very familiar with them. However does seem like your problem is a
configuration issue. Found this on stackoverflow:
https://stackoverflow.com/questions/45282608/how-to-directly-mount-nfs-share-volume-in-container-using-docker-compose-v3#tab-top

Have you used them on other containers before?

**Comment by UntouchedWagons** [comment]
I have another docker stack with NFS backed docker volumes that work fine.

**Comment by ErickGandara** [comment]
Are there any error logs?

**Comment by UntouchedWagons** [comment]
No there's nothing at all, the screenshot I included in the opening comment is all I get.

**Comment by doitandbedone** [comment]
Never ran the image in compose. Will have to run it as barebones as possible though.

**Comment by doitandbedone** [comment]
Used Composerize and got this yaml file:

```
version: '3.3'
services:
    ispyagentdvr:
        ports:
            - '8090:8090'
            - '3478:3478/udp'
            - '50000-50010:50000-50010/udp'
        volumes:
            - '/appdata/ispyagentdvr/config/:/agent/Media/XML/'
            - '/appdata/ispyagentdvr/media/:/agent/Media/WebServerRoot/Media/'
            - '/appdata/ispyagentdvr/commands:/agent/Commands/'
        environment:
            - TZ=America/Los_Angeles
        container_name: ispyagentdvr
        image: doitandbedone/ispyagentdvr
```
Take notice at the single quotes for volumes. Seems you are missing the opening ones. Also missing the UDP port. The second volumes statement again seems like it's missing entries as per the prebious link I posted too.

**Comment by UntouchedWagons** [comment]
Well that's embarrassing. But even after fixing the quotes the container still won't start

```
version: '3.3'
services:
  ispyagentdvr:
    container_name: ispyagentdvr
    image: doitandbedone/ispyagentdvr
    restart: unless-stopped
    ports:
      - '8090:8090'
      - '50000-50010:50000-50010/udp'
    volumes:
      - 'ispyagentdvr-commands:/agent/Commands/'
      - 'ispyagentdvr-data:/agent/Media/XML/'
      - 'ispyagentdvr-media:/agent/Media/WebServerRoot/Media/'
    environment:
      - 'TZ=America/Toronto'
    networks:
      - default
      - docker_default

volumes:
  ispyagentdvr-data:
  ispyagentdvr-commands:
  ispyagentdvr-media:

networks:
  default:
  docker_default:
    external: true
```

I can't forward port 3478 because my Unifi controller is using it for... something,
