### ISSUE TITLE
Error: WebRTC: ICE failed, add a TURN server and see about:webrtc for more details

### ISSUE THREAD

**Issue by TheOnionMaker** [doitandbedone/ispyagentdvr-docker#766]
**Affected Version**
latest (FROM DOCKER HUB sha256:4dd51c3266955d5ee499776a817720ad7aa4672057ec82fdf4b18c93f1ccd0d0)

**Describe the bug**
After upgrading ispyagent to latest version, it could not start, and stuck at connecting. This is error from browser console (tested on chrome, firefox, edge):

WebRTC: ICE failed, add a TURN server and see about:webrtc for more details

and this is error from docker:
StartUp: Error adding remote ICE candidate. Remote ICE candidate was empty.  1 udp 0  0 typ host generation 0

**Steps To Reproduce**
Just open the web browser and navigate to ispydvragent.

**Expected behavior**
Connect to CCTVs.

**Comment by jo-gross** [comment]
I am experiencing the same issue: after submitting the login form, it fails with the message "Try another browser" (I have tried Firefox, Chrome, and Safari), and the browser console displays the same error message as described above.

**Comment by ispysoftware** [comment]
It's due to the port range for the RTC server - new versions are using 50000 to 50100 but this docker version is only forwarding 50000 to 50010

https://github.com/doitandbedone/ispyagentdvr-docker/pull/765

**Comment by TheOnionMaker** [comment]
Actually I was forwarded 50000 to 50100 before, but the problem source was from other side. I have installed CodeProject AI but it was on IP+Port (not domain), so after upgrading the ispyconnect, it could not load.

I reinitiate the container from scratch and put AI Server behind a domain (without uncommon port) and insert the domain in the AI server location and problem resolved.

Maybe it can be another issue to be fixed?!

Thanks

**Comment by jo-gross** [comment]
@ispysoftware I’ve extended the range of the ports in my docker-compose, removed the existing container and image, pulled the latest version, and started everything again. I also cleared the browser cache but I’m still encountering the same error:

WebRTC: Using five or more STUN/TURN servers slows down discovery

Is there anything else I need to check? Do you have any idea what could be causing this issue?
Shall i provide the browsers console log?
(I access the page directly by the ip, without any certificate - if this matters)

**Comment by ispysoftware** [comment]
have you tried the docker version on the download page?

**Comment by jo-gross** [comment]
What docker version from which download page do you mean? 
I removed the container and the image and started it again. When i pull the version again, it says it up to date. 

Thats my docker-compose:
```
services:
  ispy:
    image: doitandbedone/ispyagentdvr
    container_name: ispyagentdvr
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    ports:
      - 80:8090
      - 3478:3478/udp
      - "50000-50100:50000-50100/udp"
    volumes:
      - ./config/:/agent/Media/XML/
      - ./media/:/agent/Media/WebServerRoot/Media/
      - ./commands:/agent/Commands/
```

I´ve changed the port range from 50010 to 50100, but that haven´t changed anything.

Some other system specs:
Docker version 27.3.1
Ubuntu 20.04.6 LTS
